[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "H6T3XLB35fARjZqGuxpuARFUK1Qsj2cm2L3bVAQHRJfL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mariosc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
