[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_student_intro = "GKW5wWmYXw5ZYbBPCEc3ogEKZi5ToJqtNrijMoEnhBfC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mariosc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
